### ISSUE TITLE
메인 페이지 제작

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#104]
1. 베스트 게시글들 제목 + 추천수 받아와야함
2. 갤러리의 최신 글 + 사진 받아와야함
3. 자보 받아와야함 (API)
4. 게시판에서 추천/반대가 비슷한 글들 제목 + 내용 + 추천/반대 받아와야함
5. 그릴 제목과 댓글 수 받아와야함

**Comment by Shavakan** [comment]
된거 아닌가
