### ISSUE TITLE
그릴 엔터로 입력 기능

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#110]
컨트롤 엔터로 입력이 가능하도록...

$('#textareaId').keydown(function (e) {

  if (e.ctrlKey && e.keyCode == 13) {
    // Ctrl-Enter pressed
  }
});

**Comment by Shavakan** [comment]
오 이런 꿀이슈가

**Comment by Shavakan** [comment]
Resolved by f941253a92e882b68e27f74d4d5198b4546fb0db

맥에서는 Command + Enter,
타 OS에서는 Control + Enter로 입력 가능

Chrome에서 테스트
