### ISSUE TITLE
닉네임 클릭 관련 기능

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#116]
어떤 사람의 닉네임을 클릭하면 그 사람이 작성한 게시물을 볼 수 있거나, 쪽지를 보내거나 하는 기능들이 있으면 좋을 듯 함.

**Comment by luaneyed** [comment]
'작성 글 보기' - board/all에서 search결과 띄움
'쪽지 보내기' - session에서 있던 기능을 팝업으로
