### ISSUE TITLE
All 에서 어떤 board인지 표시되지 않음

### ISSUE THREAD

**Issue by ktk1012** [sparcs-kaist/araplus#121]
현재 All에서 글을 보면 어떤 게시판인지 나오지 않는데, 카테고리 항목 대신에 게시판으로 보여주는것이 더 나을 듯 함

**Comment by sangguk2** [comment]
바꾸고 보니 내글보기도 같이 바꼈는데 좋은것같음

**Comment by luaneyed** [comment]
바꾸고 보니 내글보기도 같이 바꼈는데 좋은것같음
