### ISSUE TITLE
All에서 글쓰기 할 때 게시판 선택

### ISSUE THREAD

**Issue by luaneyed** [sparcs-kaist/araplus#123]
지금 자동으로 가비지로 설정되고 있는 것 같은데
all에서 글 쓸 때는 카테고리 뿐만 아니라 게시판까지 선택 가능하게 해 주어야 할 듯
아니면 못 쓰게 하거나

**Comment by luaneyed** [comment]
이미 올라온 이슈였는데 지우는법을 모르겟음..

**Comment by Suckzoo** [comment]
@sangguk2 굳이 지울 필요 없고 남겨두면 됩니당 ㅇㅇ
