### ISSUE TITLE
그릴에서 태그가 링크처럼 보이지 않는 문제

### ISSUE THREAD

**Issue by Shavakan** [sparcs-kaist/araplus#128]
현재 태그와 플레인텍스트가 구분하기 너무 어렵다

css를 사용해 태그가 태그인지 눈으로 보기 쉽게 만들어주자

**Comment by luaneyed** [comment]
태그는 grill이나 board나 똑같이 출력되는것같은데 board까지 포함해서 말하는거죠??

**Comment by Shavakan** [comment]
@sangguk2 넹 그렇습니다

**Comment by luaneyed** [comment]
fa09c2baa80a16ef615f909c381840dd7248b41e

#00ccff 색으로 처리했는데 색감 한번 봐주세요
원래 쓰이던 민트색 #40e0d0 과 비슷하지만 약간 다른걸로 했습니다
