### ISSUE TITLE
develop branch에서 불판에 글이 안올라갑니다. 

### ISSUE THREAD

**Issue by sparcsJara** [sparcs-kaist/araplus#131]
nodejs서버를 켜도 불판에 글이 올라가지 않습니다.

**Comment by Shavakan** [comment]
디비 마이그레이션 했나요

**Comment by ktk1012** [comment]
ctrl + enter로는댓글이 달리는데 고기 올리기 버튼을 누르면 작동을 안하네요. 
@Shavakan

**Comment by Shavakan** [comment]
@ktk1012 아니... 온클릭은 테스트해볼 생각도 못했네요 이런 버그리포트 좋아요
@sparcsJara 글이 안올라가는 문제는 아직 그대로인가요

**Comment by sparcsJara** [comment]
@Shavakan 문장에 오해의 여지가 있네요. 고기가 안올라간단 얘기였어요.

**Comment by ktk1012** [comment]
@sparcsJara 잘 됩니다. template/grill/views.html 에 socket.io 주소를 바꿔서 확인해야 합니다.

덧. 테스트용으로 주소 바꾼뒤에 그대로 커밋하지 마시오 (특히 @sparcsJara )
