### ISSUE TITLE
apps/session/views.py의 validate_nickname 함수에 print문 남아있음

### ISSUE THREAD

**Issue by pipoket** [sparcs-kaist/araplus#136]
![image](https://cloud.githubusercontent.com/assets/653592/15732155/c86258ac-28b5-11e6-99b0-9bc381c51754.png)

한글 닉네임 작성을 하니 UnicodeEncodeError가 발생하여 코드를 보니 디버그용 print문이 남아있네요.

해로운 print를 삭제해주세요~

**Comment by ktk1012** [comment]
c2a82b788308d0dc5dfd03a16174fd4d3e1be522
