### ISSUE TITLE
머릿말 기능 구현

### ISSUE THREAD

**Issue by Suckzoo** [sparcs-kaist/araplus#16]
총학/새학 등의 머릿말 기능을 구현하자.

**Comment by Shavakan** [comment]
지난 월요일 시연때 보기로는 머릿말 하나를 반드시 선택해야만 했었는데, 이 부분 수정해주시면 될 것 같습니다

**Comment by ktk1012** [comment]
da466a2cda21619ad80407ca155ed76290949f6c

**Comment by Shavakan** [comment]
머릿말 ㄴㄴ 말머리 ㅇㅇ...
