### ISSUE TITLE
Django form 기능 적용

### ISSUE THREAD

**Issue by mightydeveloper** [sparcs-kaist/araplus#2]
제가 구현한 Registration에서 email 등 validation check를 하지 않는데요,
이걸 해주는 django의 form 이란 것이 있는데 
이걸 사용해서 다시 코드를 짜보겠습니다.

**Comment by mightydeveloper** [comment]
관련 자료
https://docs.djangoproject.com/en/1.8/topics/forms/

**Comment by Shavakan** [comment]
http://github.com/sparcs-kaist/sparcssso
