### ISSUE TITLE
글쓰기 인터페이스에서 게시판 선택하는 기능 구현

### ISSUE THREAD

**Issue by Suckzoo** [sparcs-kaist/araplus#20]
1. 글쓰기 페이지에서 자신이 글을 쓸 게시판을 선택할 수 있어야 한다.
2. 게시판을 선택 -> 글쓰기 페이지로 들어가면 게시판의 기본값은 이전에 선택한 게시판이어야 한다.
3. 모든 포스트 보기 -> 글쓰기 페이지로 들어가면 게시판의 기본값은 자유게시판의 성격을 지닌 게시판이 되어야 한다. (기존 ara의 Garbage와 같은 게시판)

**Comment by ktk1012** [comment]
37d43ec9612a549c13b1d61bc0e22698feb76679

**Comment by ktk1012** [comment]
2a7feeeca8bb38828aa20f122e137ce2e76fd509
특정 보드에서 글 작성 할 때에 보던 보드가 기본 값이 되도록 하였는데 제대로 작동하지 않아 수정하였습니다.
