### ISSUE TITLE
게시글 줄바꿈 기능 구현

### ISSUE THREAD

**Issue by Suckzoo** [sparcs-kaist/araplus#22]
현재 게시글을 올릴 경우 enter에 대해 줄바꿈이 되지 않는 버그가 있다.

**Comment by rlaalstn5383** [comment]
f2a0629a7460328f8e481ef3ed9b5d4df0c378b6

**Comment by rlaalstn5383** [comment]
html 태그 등 보안 문제로 다시 엽니다.

**Comment by rlaalstn5383** [comment]
html 태그 등 보안 문제로 다시 엽니다.

**Comment by leeopop** [comment]
이거 hodduc 이가 추천한 방법대로 하면 될 것 같은데요?
https://github.com/sparcs-kaist/araplus/commit/f2a0629a7460328f8e481ef3ed9b5d4df0c378b6

"템플릿에서 {{ 내용 | linebreaksbr | safe }} 하면 한 줄로 해결할 수 있어요."
safe->force_escape

**Comment by Shavakan** [comment]
이거 어떻게 되어가고 있나요?

**Comment by ktk1012** [comment]
보드 리팩토링 이후 다시 줄바꿈 기능이 구현되어 있지 않은 것 같습니다.

**Comment by rlaalstn5383** [comment]
ce458cc6b32bdf15116b21b1a0600a3fa20e9d16
{{ content | force_escape | linebreaksbr }}로 변경했습니다.
