### ISSUE TITLE
(session) 로그인된 상태에서 /session/login 접근 가능

### ISSUE THREAD

**Issue by zealotzealot** [sparcs-kaist/araplus#27]
이미 로그인된 상태에서 /session/login url을 입력해 로그인 페이지로 이동할 수 있고 이 상태에서 로그인을 시도할 경우 다양한 에러가 발생함

**Comment by mightydeveloper** [comment]
9a7cdc2a1d8f8fa2fbeb290e7acbfa553094fa37
에서 수정하였습니다. 로그인되면 id password form이 나오지 않고 로그인이 되었다고 나오도록 수정하였고, 
로그인을 한 후 디폴트 페이지가 '/' 가 아닌 '/session/login'으로 임시로 바꾸어두었습니다.
