### ISSUE TITLE
Message 기능 명세

### ISSUE THREAD

**Issue by Shavakan** [sparcs-kaist/araplus#3]
Message
-   Content
-   Sender (fk: UserProfile)
-   Receiver (fk: UserProfile)
-   created_time
-   is_read

Features: Core
1.  A 사용자에서 B 사용자에게 메시지를 보낸다.
2.  B 사용자는 받은 메시지를 확인한다.
3.  A 사용자는 보낸 메시지를 확인한다.
Features: Convenience
4.  A 사용자는 B 사용자에게부터 오는 메시지를 차단한다.
5.  읽기 전이면 수정/삭제 가능?
6.  A 사용자는 B 사용자를 선택을 한다 (자동완성?)
7.  Board에서 아이디 우클릭으로 Receiver 설정
8.  읽음 표시
9.  Message를 확인 중에 도착하면 실시간으로 업데이트
10. Is_delivered (Front End)
11. 단체 메시지 (DB 구조 논의 필요)

**Comment by mightydeveloper** [comment]
1. #5 
2. #7 
3. #11 
4. #24 
5. 
6. 
7. 이 기능은 board쪽에서 구현해주어야 할 것 같습니다.(?)
8. #23 
9.  
10. 
11.

**Comment by mightydeveloper** [comment]
8. #23

**Comment by storykim** [comment]
6,7,9 빼고 다 구현된 거 맞나요?

**Comment by zealotzealot** [comment]
1~4, 8은 구현되었고
5는 필요없는걸로 결정되었습니다.

7은 보드 쪽에서 구현해 줘야 할 것 같고
11은 #25, #43 을 참고해주세요
6, 9, 10 이 아직 안되었네요

**Comment by storykim** [comment]
6,9는 당장 필요 없음. 10은 구현 됨.
