### ISSUE TITLE
베스트 게시판 기능

### ISSUE THREAD

**Issue by rlaalstn5383** [sparcs-kaist/araplus#38]
일정 추천수 이상의 글을 자동으로 모아주는 베스트 게시판을 만든다.

**Comment by storykim** [comment]
Description
 : 각 게시판 마다 베스트 글을 보여줌
 : 일반 view로 글을 볼 때, 베스트 글에는 특별한 표시가 있음
 : 글 모델에 is_best attribute를 추가하여 구현할 계획

**Comment by rlaalstn5383** [comment]
94e78dcdbc0e20da2ff6f90cd2e2c4d42aebd387
