### ISSUE TITLE
Group 기능 만들기 

### ISSUE THREAD

**Issue by mightydeveloper** [sparcs-kaist/araplus#43]
1. 그룹을 만드는 기능
2. 내가 속해있는 그룹들을 보는 기능
3. 내가 속해있는 그룹에서 탈퇴하는 기능
4. 그룹에 사람을 추가하는 기능

**Comment by mightydeveloper** [comment]
b66873987508c0ee5166a72316bc3a1d90e1fe70
커밋에서
1번과 2번을 구현하였습니다.

**Comment by mightydeveloper** [comment]
4번은 @zealotzealot 님이
199256a1567310f127da0f8a0164b8e39cbc958a 에서 구현하였습니다.

**Comment by rlaalstn5383** [comment]
75d2335e43acb0082bc5e5bc72065785cdf8a08a
3번 POST method로 해결했습니다..
