### ISSUE TITLE
전체 글 보기(all)에서 글쓰기로 갈 경우 All 게시판이 보이는 버그

### ISSUE THREAD

**Issue by h10public** [sparcs-kaist/araplus#51]
전체 글 보기 상태에서 글쓰기 버튼을 클릭하여 글을 쓰려고 하면 All 게시판이 보입니다. 카테고리는 board_list의 첫 번째 board에 해당하는 것들로 뜨고, 글을 작성하면 그 게시판에 글이 올라가는 것 같습니다.

이는 board를 설정해주는 드롭다운 버튼의 value가 {{current_board.board_name|default:board_list.0.board_name}}으로 되어 있는 점에서 비롯된 문제로 보입니다.

시급한 문제는 아니고, board의 전체적인 구성이 잘 파악되지 않아 수정하지 않고 일단 issue로 올려둡니다.

**Comment by rlaalstn5383** [comment]
14495e13102480da0eeb79da88be45ca8dbabb15
첫번째 게시판을 default값으로 가지게 해두었습니다.
