### ISSUE TITLE
Grill 댓글을 작성 후 새로고침 전에 표시되는 시각 포맷

### ISSUE THREAD

**Issue by zzongaly** [sparcs-kaist/araplus#55]
![image](https://cloud.githubusercontent.com/assets/4512447/8985088/7bc09c76-3710-11e5-86f4-18bae7f5409d.png)

**Comment by Shavakan** [comment]
어차피 #54처럼 할거긴 해서 크게 신경 안썼을건데...
일단 #56은 닫아주시죠
2015. 7. 30. 오후 11:13에 "zzongaly" notifications@github.com님이 작성:

**Comment by storykim** [comment]
이 문제는 '몇초전' '몇분전'으로 표시할거라서 일단 두긴했는데,
만약 마우스를 올렸을 때 정확한 시간이 뜨게 하려면 포맷을 맞추긴 해야할 것 같습니다.

**Comment by Shavakan** [comment]
넹 #56이랑 같이 제가 수정할게여
메일로 보는 중인데 아무나 어싸이니 바꿔주심 감사
2015. 7. 30. 오후 11:39에 "Story" notifications@github.com님이 작성:

**Comment by Shavakan** [comment]
698f2e5872672055d71cf01ef71d185280fd4296
@rlaalstn5383 님이 '몇초 전' '몇분 전' timeago text를 적용하면서 자연스럽게 처리되었습니다
