### ISSUE TITLE
Grill 글자수 제한 초과시 작성이 안되도록 하기

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#58]
지금은 글자수 넘어가면 -10 이런 식으로 뜨고 작성이 됩니다
(심지어 대략 500글자정도 작성해봤는데 이게 써지네요?!)

근데 저게 -로 넘어가면 버튼 자체를 막아버리는게 좋을 것 같습니다.

**Comment by Shavakan** [comment]
이것도 하는김에 제가함
어싸이니 좀
2015. 7. 30. 오후 11:41에 "Story" notifications@github.com님이 작성:

**Comment by storykim** [comment]
6889fb2
입력가능 글자수가 - 로 넘어가면 붉은 색으로 바뀌고 버튼이 비활성화됩니다.
비활성화를 사용자가 풀고 보내더라도 서버쪽에서 에러를 레이즈합니다.
