### ISSUE TITLE
Login 후 redirect

### ISSUE THREAD

**Issue by taehyun-h** [sparcs-kaist/araplus#6]
login을 요하는 기능에서 login으로 redirect 후, login을 했을 때 기존 기능으로 돌아가는 것 필요

**Comment by mightydeveloper** [comment]
c2b626133d392a3dcbc2b55480b2e086c990f731
위의 커밋에서 수정하였고
추가로 PEP 8 수정 커밋 후 develop 브렌치에 merge하였습니다.
