### ISSUE TITLE
Grill 태그 기능이 동작하지 않음

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#60]
프론트엔드를 다시 작업하다가 꼬인 것으로 추정.
각 코멘트마다 comment_{comment_order} 를 id로 가지고 있었는데, _가 - 로 바뀜
태그를 추가하는 부분에서 _ 를 - 로 바꾸면 해결.

**Comment by Shavakan** [comment]
정화캄
2015. 7. 31. 오전 12:01에 "Story" notifications@github.com님이 작성:

**Comment by storykim** [comment]
df40083
solved.
