### ISSUE TITLE
Tag Comment 미리보기

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#62]
현재 @ + 숫자를 통해 태그가 가능한데,
코멘트를 작성 도중 @숫자 를 입력하면 그 숫자에 해당하는 코멘트가 미리보기되면 좋을 것 같음.

**Comment by taehyun-h** [comment]
8e318aebeb67afd04fe38ddbb46fe5754ff32e63

이걸로 보드쪽에는 했습니다.

그릴쪽도 할게요.
