### ISSUE TITLE
글에 태그 기능

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#64]
구체적으로 논의해봐야겠지만,
1. 글에 태그를 몇 개 달 수 있다.
2. 각 태그를 클릭하면 똑같은 태그가 달린 다른 글들을 보여준다.
3. 태그로 검색할 수 있다.

정도의 기능이 필요할 것 같음.

**Comment by storykim** [comment]
해시태그와 같은 방식으로 구현.

**Comment by leeopop** [comment]
아 이걸 보니 멀티태그 계획이 있는거같군요

**Comment by leeopop** [comment]
이럴땐 아예 모든 정보를 태그로 해놓는것도 좋습니다.
내부적으로 보이진 않지만 관리하는 태그를 두면 나중에 검색할 때 한가지 필드로 검색할 수 있어요.
예를들면 어떤 댓글에 대하여 #parent:1234 로 두어서 1234번 글의 댓글이다를 나태내거나.

**Comment by storykim** [comment]
음 그럼 일반적인 태그는 #tag:blabla 이런식으로 들어가있는 개념인가요?

**Comment by leeopop** [comment]
어어 그런식으로 하면 될꺼에요 아마
구현은 개발자 마음대로

**Comment by storykim** [comment]
7998dae / 30bfe91
naive하게는 돌아가는데, 현재는 글을 수정할 때마다 해시태그 테이블을 모두 지웠다가 다시 생성합니다. 더 나은 방법이 필요할 듯 합니다.
