### ISSUE TITLE
대댓글 기능 삭제

### ISSUE THREAD

**Issue by taehyun-h** [sparcs-kaist/araplus#69]

**Comment by taehyun-h** [comment]
8.3일 회의 결과 댓글에서 태그가 가능하면 대댓글 기능이 필요가 없다는 결론이 나서 삭제하기로 했습니다.

**Comment by taehyun-h** [comment]
ff9cb9496bfa644f09656d6a0f273e083256900a

**Comment by leeopop** [comment]
멀티 태그는 지원할 계획인가요?
[@글쓴이 @익명1 @익명3] 요런식으로
