### ISSUE TITLE
활동 로그 기능

### ISSUE THREAD

**Issue by ktk1012** [sparcs-kaist/araplus#71]
1. 유저가 작성한 글 및 댓글을 작성한 글을 확인 할 수 있는 활동 로그를 만든다.
2. 활동 로그와 함께 새 댓글이 달렸을 때 알람(웹 노티)를 받을 수 있도록 하며, 사용자가 원하면 받지 않도록 한다.

**Comment by ktk1012** [comment]
#73 
1번 구현하였습니다.

**Comment by storykim** [comment]
33ed694
2번 완료.
