### ISSUE TITLE
댓글 태그 기능 수정시 버그

### ISSUE THREAD

**Issue by taehyun-h** [sparcs-kaist/araplus#77]
댓글 태그를 사용한 댓글을 수정하려는 경우 html태그가 그대로 나타남

**Comment by ktk1012** [comment]
modify 버튼 클릭했을 때 에러 나는데 한 번 확인좀 해주세요

**Comment by ktk1012** [comment]
버튼의 id가 현재 content id도 되어있는데 이 부분을 order로 바꿔줘야 할 듯 합니다. 기왕이면 모든 element의 id순서를 comment order로 바꿔 주는게 나을 듯 싶네여

**Comment by ktk1012** [comment]
37d6e856709b59f45e100232d42eb766ed664bdd 
일단 임시로 해결해 두었습니다.
