### ISSUE TITLE
썸네일 표시

### ISSUE THREAD

**Issue by storykim** [sparcs-kaist/araplus#89]
1. 채널들의 리스트가 있는 페이지에서 각 채널의 썸네일을 보여줘야한다.
2. 채널에 들어갔을 때 각각의 글에 알맞는 썸네일을 보여줘야한다.

썸네일 업로드는 구현된 상황.

**Comment by rlaalstn5383** [comment]
7724c8de505fbe466e9f6fd470873cf02aeb93bb
1, 2 구현했습니다

**Comment by rlaalstn5383** [comment]
썸네일 리사이즈 후 저장, 같은 이름 썸네일 업로드 됐을 때 처리 해야 합니다.

**Comment by h10public** [comment]
5219dd7c8793264f6957befbcc0616d5569e6f3e 로 처리된 것 같습니다. 확인해보시고 문제 있는 경우 이슈 열어주세요.
